language: csharp
dotnet: 2.1.502
mono: latest
os: linux
dist: xenial
sudo: enabled
before_install:
  - chmod +x build.sh
script:
  - "./build.sh"
env:
  global:
    - secure: pWK600z73MmGBoisExlPArY1EKANhyckfiYu5ODHXLGVefkqrujNhf7O2LXel4w6XjdO/mc9pLK7XLkWfsO7EMHNmsTuRtUkSRVs7H6rfT76FZ1Zc9h8usVPOhQrRVAWpKkZfpDQjEw9onSjkqJAHQ1uYgoU8TUOvIMkuPwyx1tWJsaM11hJQ4BCsCN0Hlv1NWTMWvKFdEK41KfK6KAC2vKHVG8N0mZFYUHTfNjHcicIHkgociZq6GEQOAYTCUHZUbezHyqV7UFH5UjyWT11wciB7tAgeHtYpvoRrDFyTH36yjuwKNjUR/XjOYvPS8Z8MV9PwsS/8pw71MHu32ajVuUmkCSrelA5UfFKH+1QaV/TPL4bRwt3S+IU7GGGXgdfpSPUWkvjNmiNsi/x4wdvYlHf0dGpO/bE43jJIJM4zLeRSPMl7soYNcoJIHQ4LYxZq0LWw7R6qWMpQmlelSObWucMCpXIkbX2hBkKMfMr1mPhEdAi63pSoY3sSOZmerfzwe1SDcKTEJFjZwthFJTB+xTyUeUUEdKVaVjHFuBB+ouz1uCeeGEmWlYLe2q7CnLPGmS3E+a+OOmY12s3zlNDuAEsNvKwsNUoZ/HDuhsJdNfiuo6KiYPrYdH4Do/2/Zn0/1PbCa/LYsiR9Dehm9GTza8I79fNQe4r4x1yLfPVMOs=
branches:
  only:
    - master
    - develop
