language: csharp
dotnet: 2.1.502
mono: none
os: linux
dist: xenial
sudo: enabled
before_install:
  - chmod +x build.sh
script:
  - "./build.sh"
env:
  - PACKAGE_VERSION: 0.2.0-beta03
branches:
  only:
    - master
    - develop
