language: csharp
dotnet: 2.2.101
sudo: enabled
before_install:
  - chmod +x build.sh
script:
  - "./build.sh"
env:
  global:
    - secure: g6SlSUPQDyeWQDjel7SgmN09todxHYwW+uVESp5vpFHKUQLRxg0m6fIbiz4AZH/TkLRgfcBYY1Y421yBXnZGCjXC4I8+VBheow20a80woAEhDYGvtgTFh1kuA6z/I5DajudrFaV4rIe+yJQuHxl0eG9fXD6SpXjsV1Rpblq/2ONkDaZ2fwaMrPO6+AM0TEN35oAa9Z9gkinGUtZVPVb21m0mKCfFfNtk8FcT74T1Pb1Jo3JqOy0b4paIPtj0UFccLqVNrVWTieEmrkk5T2gs4CrWvkg2izKfoeeNjeGXomGk5OWbMze1n3W1A50JmMCLAquprbr00+VGkLpGvAAIZL8jWtgX0nnLmlLEVDI3+Ryda1KbkJbjroDGJhTpqN1B4H0RNWubihLBBrQDFR1CqdbPruHf0FD7Ni5KCd9vb1vDK3ro9RG4gh0JEFPidefteC5XpfAVCX2Nk9IHd4cKseuddBhDOIkZPqDhYr213DusgBq3jaKxR0D4o8asp0q2HxuLwUfbbS2F5LFzBzxSsk96JEBoOReUqtU0Uc1ZuTjR2AuUddUqw8c3joYqQ3M083FOTiqSjm75C02+q/aSoN7IXJHI7AuF5amXK6ueBrQX3IW4KYqkJShtSfYZYlibbjE0RuG0cQO1Q2BPaV9zYbbKXYckV7KFrWV77mAXyiY=
