name: Qodana (.NET)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Qodana Scan (.NET)"
        uses: JetBrains/qodana-action@v2024.3
        with:
          linter: jetbrains/qodana-cdnet:2024.3

      - name: "Upload SARIF to GitHub Security"
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
